package com.asim.finance.service;

import com.asim.finance.entity.Expense;
import com.asim.finance.entity.User;
import com.itextpdf.text.*;
import com.itextpdf.text.pdf.*;
import com.itextpdf.text.Element;

import org.springframework.stereotype.Service;

//import javax.lang.model.element.Element;
import java.io.ByteArrayInputStream;
import java.io.ByteArrayOutputStream;
import java.time.LocalDate;
import java.util.List;

@Service
public class PdfServiceImpl implements PdfService {

    private final ExpenseService expenseService;
    private final IncomeService incomeService;

    public PdfServiceImpl(
            ExpenseService expenseService,
            IncomeService incomeService
    ) {

        this.expenseService = expenseService;
        this.incomeService = incomeService;

    }

    @Override
    public ByteArrayInputStream generateReport(User user) {

        Document document = new Document();

        ByteArrayOutputStream out = new ByteArrayOutputStream();

        try {

            PdfWriter.getInstance(document, out);

            document.open();

            Font titleFont =
                    FontFactory.getFont(
                            FontFactory.HELVETICA_BOLD,
                            22
                    );

            Font headingFont =
                    FontFactory.getFont(
                            FontFactory.HELVETICA_BOLD,
                            16
                    );

            Font normalFont =
                    FontFactory.getFont(
                            FontFactory.HELVETICA,
                            12
                    );

            Paragraph title =
                    new Paragraph(
                            "PERSONAL FINANCE REPORT",
                            titleFont
                    );

            title.setAlignment(Element.ALIGN_CENTER);

            document.add(title);

            document.add(new Paragraph(" "));

            document.add(
                    new Paragraph(
                            "User : " + user.getFullName(),
                            normalFont
                    )
            );

            document.add(
                    new Paragraph(
                            "Email : " + user.getEmail(),
                            normalFont
                    )
            );

            document.add(
                    new Paragraph(
                            "Generated : " + LocalDate.now(),
                            normalFont
                    )
            );

            document.add(new Paragraph(" "));

            double income =
                    incomeService.getTotalIncome(user);

            double expense =
                    expenseService.getTotalExpense(user);

            double balance =
                    income - expense;

            document.add(
                    new Paragraph(
                            "Total Income : ₹ " + income,
                            headingFont
                    )
            );

            document.add(
                    new Paragraph(
                            "Total Expense : ₹ " + expense,
                            headingFont
                    )
            );

            document.add(
                    new Paragraph(
                            "Balance : ₹ " + balance,
                            headingFont
                    )
            );

            document.add(new Paragraph(" "));

            PdfPTable table = new PdfPTable(4);

            table.setWidthPercentage(100);

            table.addCell("Title");
            table.addCell("Category");
            table.addCell("Amount");
            table.addCell("Date");

            List<Expense> expenses =
                    expenseService.getUserExpenses(user);

            for (Expense e : expenses) {

                table.addCell(e.getTitle());

                table.addCell(e.getCategory());

                table.addCell(
                        String.valueOf(e.getAmount())
                );

                table.addCell(
                        String.valueOf(e.getDate())
                );

            }

            document.add(table);

            document.add(new Paragraph(" "));

            Paragraph footer =
                    new Paragraph(
                            "Generated by Finance Management System",
                            normalFont
                    );

            footer.setAlignment(Element.ALIGN_CENTER);

            document.add(footer);

            document.close();

        }

        catch (Exception ex) {

            ex.printStackTrace();

        }

        return new ByteArrayInputStream(out.toByteArray());

    }

}